module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Watches', [{
      title: 'Nikita',
      image: '100.jpg',
      category: 'Мужские',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Nikita по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья. Мастера команды Studio MART подходят у выполнению каждого заказа индивидуально, что позволяет идеально "посадить" часы на вашу руку с учётом дополнительных пожеланий.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Polina',
      image: '102.jpg',
      category: 'женские',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Женские серебряные часы с объемной аппликацией на циферблате в виде цветка камелии. Каждый лепесток вручную вырезан из серебряной пластины, изящно изогнут и покрыт белоснежной эмалью. Фоном для камелии служит радужный перламутр.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Gosha',
      image: '104.jpg',
      category: 'Мужские',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Kirill по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Kadzhik',
      image: '105.jpg',
      category: 'Мужские',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Kadzhik по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Baga',
      image: '106.jpg',
      category: 'Унисекс',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Baga по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Leha',
      image: '107.jpg',
      category: 'Унисекс',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Leha по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Max',
      image: '108.jpg',
      category: 'Унисекс',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Max по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Pavel',
      image: '109.jpg',
      category: 'Унисекс',
      case: 'сталь',
      strap: 'натуральная кожа',
      glass: 'минеральное',
      mechanism: 'ручной завод',
      water: '30WR',
      description: 'Модель Pavel по праву можно считать унисекс. Это часы, которые здорово смотрятся как на мужском запястье, так и на женском, вне зависимости от размеров запястья.',
      price: 7452,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkInsert('Watches', null, {});
  },
};
